#!/bin/sh

trap 'update' 5

delim="|"
counter=0

status(){
    echo " "
    amixer get Master | grep -o "[0-9]*%\|\[on\]\|\[off\]" | head -2 |sed "s/\[on\]//;s/\[off\]//"

    # Show unread mail if mutt-wizard is installed.
#    command -v mw >/dev/null 2>&1 &&
#        echo "$delim" &&
#        du -a ~/.local/share/mail/*/INBOX/new/* 2>/dev/null | wc -l | sed 's/^/Mail:/'
#        echo "$delim"
    echo "$delim"
    sensors | grep Package | awk '{print substr($4,2)}'
    echo "$delim"



    # Date and time.
    date '+%d.%m.%Y %H:%M'
}

update() {
    # So all that big status function was just a command that quicking gets
    # what we want to be the statusbar. This xsetroot command is what sets
    # it. Note that the tr command replaces newlines with spaces. This is
    # to prevent some weird issues that cause significant slowing of
    # everything in dwm. Note entirely sure of the cause, but again, the tr
    # command easily avoids it.
    xsetroot -name "$(status | tr '\n' ' ')" &
    wait
}

while :; do
    update
    sleep 15s &
    wait
done
